kdv/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'kdv'
urlpatterns = [
    path('', views.LedgerView.as_view(), name='ledger'),
    path('add_record/', views.AddRecordView.as_view(), name='add_record'),
    path('buy/<int:barcode>/', views.BuyProductView.as_view(), name='buy_product'),
    path('challenge/<int:pk>/', views.ChallengeTransactionView.as_view(), name='challenge_transaction'),
    path('unchallenge/<int:pk>/', views.UnChallengeTransactionView.as_view(), name='unchallenge_transaction'),
    path('return/<int:pk>/', views.ReturnTransactionView.as_view(), name='return_transaction'),
    path('revoke/<int:pk>/', views.RevokeRecordView.as_view(), name='revoke_record'),
    path('add_transaction/', views.AddTransactionView.as_view(), name='add_transaction'),
    path('productlist/', views.ProductListView.as_view(), name='productlist'),
    path('account/', views.AccountView.as_view(), name='account'),
]

kdv/models.py
from django.db import models
from django.conf import settings


def to_currency(value):
    currency_format = settings.CURRENCY_FORMAT if hasattr(settings, 'CURRENCY_FORMAT') else "{0}{1}.{2:02}€"
    currency_factor = settings.CURRENCY_FACTOR if hasattr(settings, 'CURRENCY_FACTOR') else 100
    return currency_format.format("-" if value < 0 else "", abs(value) // currency_factor, abs(value) % currency_factor)

class AccountManager(models.Manager):
    """A manager for accounts
    """
    def current(self, user):
        if user.is_authenticated:
            account, created = self.get_or_create(user=user)
            return account
        return None

class Account(models.Model):
    """An account which can hold records and transactions.
    """
    objects = AccountManager()
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True)

    def saldo(self):
        cost = Record.objects.filter(account=self).exclude(state=Record.REVOKED).aggregate(models.Sum('cost')).get('cost__sum') or 0
        sent = Transaction.objects.filter(acc_from=self).exclude(state=Transaction.RETURNED).aggregate(models.Sum('value')).get('value__sum') or 0
        recv = Transaction.objects.filter(acc_to=self).exclude(state=Transaction.RETURNED).aggregate(models.Sum('value')).get('value__sum') or 0
        return recv - cost - sent;

    def currency(self):
        return to_currency(self.saldo())

    def __str__(self):
        if self.user:
            return self.user.username
        else:
            return "Account #{0}".format(self.pk)

class Transaction(models.Model):
    """A transaction from one account to another
    """
    ACTIVE = 'AC'
    CHALLENGED = 'CH'
    RETURNED = 'RT'

    STATE_CHOICES = (
        (ACTIVE, 'Active'),
        (CHALLENGED, 'Challenged'),
        (RETURNED, 'Returned'),
    )

    registered = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    acc_from = models.ForeignKey('Account', on_delete=models.PROTECT, related_name='transaction_set_out')
    acc_to = models.ForeignKey('Account', on_delete=models.PROTECT, related_name='transaction_set_in')

    value = models.PositiveIntegerField()
    state = models.CharField(max_length=2, choices=STATE_CHOICES, default=ACTIVE)

    def currency(self):
        return to_currency(self.value)

    def inv_currency(self):
        return to_currency(-self.value)

    def type(self):
        return "transaction"

    def __str__(self):
        return "{0} -> {1} ({2})".format(self.acc_from, self.acc_to, self.currency())


class RecordManager(models.Manager):
    """Manager for records
    """
    def record(self, account, barcode, name, cost, amount=1, **kwargs):
        if not type(amount) == int:
            raise ValueError("Amount not an Integer: {0}".format(amount))
        elif amount <= 0:
            raise ValueError("Invalid Amount: {0}".format(amount))
        elif amount > 1:
            name = "{0}x {1}".format(amount, name)
            cost = cost * amount
        record = self.create(account=account, barcode=barcode, name=name, cost=cost, **kwargs)
        record.save()


class Record(models.Model):
    """A record for buying an item. The ba
    """
    objects = RecordManager()

    ACTIVE = 'AC'
    REVOKED = 'RV'
    STATE_CHOICES = (
        (ACTIVE, 'Active'),
        (REVOKED, 'Revoked'),
    )

    registered = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    barcode = models.PositiveIntegerField()
    name = models.CharField(max_length=100)

    cost = models.IntegerField()
    state = models.CharField(max_length=2, choices=STATE_CHOICES, default=ACTIVE)

    account = models.ForeignKey('Account', on_delete=models.PROTECT)

    def type(self):
        return "record"

    def currency(self):
        return to_currency(self.cost)

    def inv_currency(self):
        return to_currency(-self.cost)

    def __str__(self):
        return "{0} ({1})".format(self.name, self.currency())


class Category(models.Model):
    """A category for products
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
    """A product, which can be bought
    """
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    barcode = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    cost = models.IntegerField()
    storage = models.IntegerField(default=0)

    def currency(self):
        return to_currency(self.cost)

    def __str__(self):
        return "{0} ({1}) [{2}]".format(self.name, self.currency(), self.barcode)

kdv/templates/kdv/account.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}
  {% trans "account" as tr_account %}
  <h2>{{tr_account|capfirst}}</h2>
  {{ account.user.username }}
{% endblock %}

kdv/templates/kdv/add_record.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}
  {% trans "add record" as tr_add_record %}
  <h2>{{tr_add_record|capfirst}}</h2>
  <form method="POST">
    {{form}}
    {% csrf_token %}
    <button type="submit">{% trans "record" %}</button>
  </form>
{% endblock %}

kdv/templates/kdv/add_transaction.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}
  {% trans "add transaction" as tr_add_transaction %}
  <h2>{{tr_add_transaction|capfirst}}</h2>
  <form method="POST">
    {{form}}
    {% csrf_token %}
    <button type="submit">{% trans "confirm" %}</button>
  </form>
{% endblock %}

kdv/templates/kdv/base.html
{% extends "kdv/html.html" %}

{% block wrapper %}
  {% block page %}
    {% include "kdv/navbar.html" %}
    {% block content %}
      kdv:base: no 'content' block provided!
    {% endblock %}
  {% endblock %}
{% endblock %}

kdv/templates/kdv/buy_product.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}
  {% trans "buy product" as tr_buy_product %}
  <h2>{{tr_buy_product|capfirst}}</h2>

  <div class="product">
    <dl>
      <dt>{% trans 'barcode' as tr_price %}{{tr_price|capfirst}}</dt><dd>{{object.barcode}}</dd>
      <dt>{% trans 'name' as tr_price %}{{tr_price|capfirst}}</dt><dd>{{object.name}}</dd>
      <dt>{% trans 'price' as tr_price %}{{tr_price|capfirst}}</dt><dd>{{object.currency}}</dd>
    </dl>
  </div>

  <form method="POST">
    {{form}}
    {% csrf_token %}
    <button type="submit">{% trans "record" %}</button>
  </form>
{% endblock %}

kdv/templates/kdv/confirm.html
<h2>{{title}}</h2>
<form method="POST">
  <p>{{intro}}</p>
  {{form}}
  {% csrf_token %}
  <button type="submit">{{submit}}</button>
</form>

kdv/templates/kdv/html.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}KdV{% endblock %} - KdV</title>
  </head>
  <body>
    {% block wrapper %}
    kdv:html: No 'wrapper' content block provided.
    {% endblock %}
  </body>
</html>

kdv/templates/kdv/ledger.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}

  <h2><strong>Saldo</strong>:
    {% if account.saldo > 0 %}
    <span class="text-success">{{account.currency}}</span>
    {% elif account.saldo < 0 %}
    <span class="text-danger">{{account.currency}}</span>
    {% else %}{{account.currency}}{% endif %}
  </h2>
  <table class="table table-ledger">
    {% spaceless %}
    {% for entry in ledger %}
    <tr>
      <td>{{entry.registered|date:"d.m.Y H:i:s e"}}</td>
      {% if entry.type == "transaction" %}
      {% if entry.acc_to == account %}
      {% if entry.acc_from == account %}
      <td colspan="4">Self-Transaction</td>
      {% else %}
      <td></td>
      <td>Transaction from {{entry.acc_from}}</td>
      <td class="text-success">{{entry.currency}}</td>
      <td>
        {% if entry.state == 'AC' %}
          {% trans "return" as tr_return %}
          <a href="#">{{tr_return|capfirst}}</a>
        {% elif entry.state == 'CH' %}
          {% trans "return challenged" as tr_return_challenged %}
          <a href="#">{{tr_return_challenged|capfirst}}</a>
        {% else %}
          {% trans "returned" as tr_returned %}
          <strong>{{tr_returned|capfirst}}</strong>
        {% endif %}
      </td>
      {% endif %}
      {% else %}
      <td></td>
      <td>Transaction to {{entry.acc_to}}</td>
      <td class="text-danger">{{entry.inv_currency}}</td>
      <td>
        {% if entry.state == 'AC' %}
          {% trans "challenge" as tr_challenge %}
          <a href="#">{{tr_challenge|capfirst}}</a>
        {% elif entry.state == 'CH' %}
          {% trans "unchallange" as tr_unchallenge %}
          <a href="#">{{tr_unchallenge|capfirst}}</a>
        {% else %}
          {% trans "returned" as tr_returned %}
          <strong>{{tr_returned|capfirst}}</strong>
        {% endif %}
      </td>
      {% endif %}
      {% elif entry.type == "record" %}
      <td>{{entry.barcode}}</td>
      <td>{{entry.name}}</td>
      {% if entry.cost > 0 %}
      <td class="text-danger">
      {% elif entry.cost < 0 %}
      <td class="text-success">
      {% else %}<td>{% endif %}
      {{entry.inv_currency}}
      </td>
      <td>
        {% if entry.state == 'AC' %}
          {% trans "revoke" as tr_revoke %}
          <a href='#'>{{tr_revoke|capfirst}}</a>
        {% else %}
          {% trans 'revoked' as tr_revoked %}
          <strong>{{tr_revoked|capfirst}}</strong>
        {% endif %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
    {% endspaceless %}
  </table>
{% endblock %}

kdv/templates/kdv/navbar.html
<div class="navbar">
  <a href="{% url 'kdv:ledger' %}">Ledger</a>
  <a href="{% url 'kdv:add_record' %}">Add Record</a>
  <a href="{% url 'kdv:add_transaction' %}">Add Transaction</a>
  <a href="{% url 'kdv:productlist' %}">Add Transaction</a>
  <a href="{% url 'kdv:account' %}">Account</a>
</div>

kdv/templates/kdv/product_list.html
{% extends "kdv/base.html" %}{% load i18n sekizai_tags %}

{% block page %}
  {% addtoblock "css" %}
    <style type="text/css">
      .table-products tr.category { background-color: #eee; }
    </style>
  {% endaddtoblock %}

  {% trans "productlist" as tr_productlist %}
  {% trans "buy" as tr_buy %}
  <h2>{{tr_productlist|capfirst}}</h2>
  <table class="table table-bordered table-products">
    <tr>
      <th>{% trans "code" as tr_code %}{{tr_code|capfirst}}</th>
      <th>{% trans "name" as tr_code %}{{tr_code|capfirst}}</th>
      <th>{% trans "price" as tr_code %}{{tr_code|capfirst}}</th>
      <th>{% trans "store" as tr_code %}{{tr_code|capfirst}}</th>
      <th>{% trans "action" as tr_code %}{{tr_code|capfirst}}</th>
    </tr>
  	{% for cat in categories %}
  	<tr class="category"><th colspan="5">{{cat.name}}</th></tr>
    {% for product in cat.product_set.all %}
    <tr>
      <td>{{product.barcode}}</td>
      <td>{{product.name}}</td>
      <td>{{product.currency}}</td>
      <td>{{product.storage}}</td>
      <td><a class="btn btn-success" href="{% url 'kdv:buy_product' product.barcode %}">{{tr_buy|capfirst}}</a></td>
    </tr>
    {% endfor %}
  	{% endfor %}
  </table>
{% endblock %}

kdv/templates/kdv/revoke_record.html
{% extends "kdv/base.html" %}{% load i18n %}

{% block page %}
  {% trans "revoke" as tr_revoke %}
  {% trans "time" as tr_time %}
  {% trans "name" as tr_name %}
  {% trans "amount" as tr_amount %}
  {% trans "revoke record" as tr_revoke_record %}

  <h2>{{tr_revoke_record|capfirst}}</h2>
  <dl>
    <dt>{{tr_time|capfirst}}</dt><dd>{{object.registered|date:'d.m.Y H:i:s e'}}</dd>
    <dt>{{tr_name|capfirst}}</dt><dd>{{object.name}}</dd>
    <dt>{{tr_amount|capfirst}}</dt><dd>{{object.currency}}</dd>
  </dl>
  {% include "kdv/confirm.html" with submit=tr_revoke|capfirst %}
{% endblock %}